version: '3.4'

name: HappYnessProject
services:
  db:
    image: mongo:5.0
    ports:
      - "28017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - happy_network

  hp.api:
    image: ${DOCKER_REGISTRY-}hpapi
    build:
      context: .
      dockerfile: HP.Api/Dockerfile
    depends_on:
      - db
    networks:
      - happy_network

  hp.blazor:
    image: ${DOCKER_REGISTRY-}blazorui
    build:
      context: .
      dockerfile: BlazorUI/Dockerfile
    depends_on:
      - db
    ports:
      - "5555:80"
    networks:
      - happy_network

  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - happy_network

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - happy_network
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
   



networks:
  happy_network:
    name: happiness_bridge
    driver: bridge



