version: '3.4'

services:
  db:
    image: mongo:5.0
    ports:
      - 28017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  hp.api:
    image: ${DOCKER_REGISTRY-}hpapi
    build:
      context: .
      dockerfile: HP.Api/Dockerfile
    depends_on:
      - db
  hp.blazor:
    image: ${DOCKER_REGISTRY-}blazorui
    build:
      context: .
      dockerfile: BlazorUI/Dockerfile
    depends_on:
      - db
    ports:
      - 5555:80
